-- Sample scholarship data for testing the application
-- This file contains INSERT statements to populate the scholarships table with realistic sample data

INSERT INTO scholarships (
  title, 
  description, 
  university, 
  country, 
  degree_level, 
  field_of_study, 
  funding_type, 
  amount, 
  deadline, 
  application_url, 
  eligibility_criteria, 
  is_active, 
  created_at, 
  updated_at
) VALUES
  (
    'Rhodes Scholarship at Oxford University',
    'The Rhodes Scholarship is one of the oldest and most prestigious international scholarship programmes, providing full financial support for selected students to study at the University of Oxford.',
    'University of Oxford',
    'United Kingdom',
    'graduate',
    ARRAY['Any Field', 'Humanities', 'Sciences', 'Engineering'],
    'full_scholarship',
    60000,
    '2024-10-01 23:59:59+00',
    'https://www.rhodeshouse.ox.ac.uk/',
    ARRAY['Outstanding academic achievement', 'Leadership potential', 'Commitment to service', 'Age 18-24', 'Undergraduate degree'],
    true,
    NOW(),
    NOW()
  ),
  (
    'Fulbright U.S. Student Program',
    'The Fulbright U.S. Student Program provides opportunities for recent graduates and graduate students to study, conduct research, and teach English abroad.',
    'Various Universities',
    'United States',
    'graduate',
    ARRAY['Education', 'International Relations', 'Public Policy', 'STEM'],
    'full_scholarship',
    35000,
    '2024-09-15 23:59:59+00',
    'https://us.fulbrightonline.org/',
    ARRAY['U.S. citizenship', 'Bachelor\'s degree', 'Language proficiency', 'Academic excellence'],
    true,
    NOW(),
    NOW()
  ),
  (
    'DAAD Study Scholarships',
    'The German Academic Exchange Service (DAAD) offers scholarships for international students to pursue graduate studies in Germany.',
    'Various German Universities',
    'Germany',
    'graduate',
    ARRAY['Engineering', 'Natural Sciences', 'Computer Science', 'Economics'],
    'partial_scholarship',
    850,
    '2024-11-30 23:59:59+00',
    'https://www.daad.de/en/',
    ARRAY['Bachelor\'s degree', 'Academic excellence', 'German language skills preferred', 'Research proposal'],
    true,
    NOW(),
    NOW()
  ),
  (
    'Erasmus Mundus Joint Master Degrees',
    'Erasmus Mundus offers prestigious, integrated, international study programmes taught by an international consortium of higher education institutions.',
    'European Universities Consortium',
    'Various European Countries',
    'graduate',
    ARRAY['European Studies', 'Technology', 'Environmental Sciences', 'Business'],
    'full_scholarship',
    45000,
    '2024-12-15 23:59:59+00',
    'https://ec.europa.eu/programmes/erasmus-plus/',
    ARRAY['Bachelor\'s degree', 'English proficiency', 'Academic merit', 'EU eligibility or third-country nationals'],
    true,
    NOW(),
    NOW()
  ),
  (
    'Australia Awards Scholarships',
    'Australia Awards Scholarships provide opportunities for people from developing countries to undertake full-time undergraduate or postgraduate study at participating Australian universities.',
    'Australian Universities',
    'Australia',
    'both',
    ARRAY['Public Policy', 'Health', 'Agriculture', 'Education', 'Engineering'],
    'full_scholarship',
    50000,
    '2024-08-31 23:59:59+00',
    'https://www.australiaawards.gov.au/',
    ARRAY['Developing country citizenship', 'Academic merit', 'Leadership potential', 'Return to home country commitment'],
    true,
    NOW(),
    NOW()
  ),
  (
    'Chevening Scholarships',
    'Chevening Scholarships are the UK government\'s global scholarship programme, funded by the Foreign and Commonwealth Office and partner organisations.',
    'UK Universities',
    'United Kingdom',
    'graduate',
    ARRAY['Politics', 'International Relations', 'Law', 'Economics', 'Public Administration'],
    'full_scholarship',
    55000,
    '2024-11-07 23:59:59+00',
    'https://www.chevening.org/',
    ARRAY['Bachelor\'s degree', 'Two years work experience', 'English language requirement', 'Leadership potential'],
    true,
    NOW(),
    NOW()
  ),
  (
    'Vanier Canada Graduate Scholarships',
    'The Vanier Canada Graduate Scholarships program attracts and retains world-class doctoral students and establishes Canada as a global centre of excellence in research and higher learning.',
    'Canadian Universities',
    'Canada',
    'phd',
    ARRAY['Health Research', 'Natural Sciences', 'Engineering', 'Social Sciences'],
    'fellowship',
    50000,
    '2024-11-01 23:59:59+00',
    'https://vanier.gc.ca/',
    ARRAY['PhD enrollment or application', 'Academic excellence', 'Research potential', 'Leadership skills'],
    true,
    NOW(),
    NOW()
  ),
  (
    'Swiss Government Excellence Scholarships',
    'The Swiss Government Excellence Scholarships promote international exchange and research cooperation between Switzerland and over 180 countries.',
    'Swiss Universities',
    'Switzerland',
    'graduate',
    ARRAY['Fine Arts', 'Music', 'Research', 'Sciences', 'Technology'],
    'partial_scholarship',
    1920,
    '2024-12-31 23:59:59+00',
    'https://www.sbfi.admin.ch/',
    ARRAY['Master\'s or PhD application', 'Academic excellence', 'Research proposal', 'Language requirements'],
    true,
    NOW(),
    NOW()
  ),
  (
    'New Zealand Development Scholarships',
    'New Zealand Development Scholarships provide citizens of developing countries with opportunities to gain knowledge, skills and qualifications in areas that will assist in the development of their home countries.',
    'New Zealand Universities',
    'New Zealand',
    'both',
    ARRAY['Development Studies', 'Agriculture', 'Health', 'Education', 'Engineering'],
    'full_scholarship',
    40000,
    '2024-09-30 23:59:59+00',
    'https://www.mfat.govt.nz/',
    ARRAY['Developing country citizenship', 'Academic merit', 'Relevant work experience', 'Development impact potential'],
    true,
    NOW(),
    NOW()
  ),
  (
    'Gates Cambridge Scholarships',
    'Gates Cambridge Scholarships are among the most prestigious international scholarships in the world, providing full funding for outstanding applicants from outside the UK to pursue a graduate degree at the University of Cambridge.',
    'University of Cambridge',
    'United Kingdom',
    'graduate',
    ARRAY['Any Field', 'Sciences', 'Technology', 'Humanities', 'Social Sciences'],
    'full_scholarship',
    65000,
    '2024-10-14 23:59:59+00',
    'https://www.gatescambridge.org/',
    ARRAY['Outstanding academic achievement', 'Leadership potential', 'Commitment to improving lives', 'Non-UK citizenship'],
    true,
    NOW(),
    NOW()
  ),
  (
    'MEXT Japanese Government Scholarships',
    'The Japanese Government (MEXT) Scholarship is offered to international students who want to study at Japanese universities as undergraduate or graduate students.',
    'Japanese Universities',
    'Japan',
    'both',
    ARRAY['Japanese Studies', 'Engineering', 'Sciences', 'Technology', 'Cultural Studies'],
    'full_scholarship',
    48000,
    '2024-06-14 23:59:59+00',
    'https://www.mext.go.jp/',
    ARRAY['Academic excellence', 'Japanese language study commitment', 'Age requirements', 'Health certificate'],
    true,
    NOW(),
    NOW()
  ),
  (
    'Netherlands Fellowship Programme',
    'The Netherlands Fellowship Programme (NFP) is designed for mid-career professionals from developing countries and aims to strengthen human institutional capacity in these countries.',
    'Dutch Universities',
    'Netherlands',
    'graduate',
    ARRAY['Public Administration', 'Health', 'Education', 'Environment', 'Water Management'],
    'full_scholarship',
    42000,
    '2024-05-01 23:59:59+00',
    'https://www.nuffic.nl/',
    ARRAY['Developing country nationality', 'Bachelor\'s degree', 'Work experience', 'Employer support'],
    true,
    NOW(),
    NOW()
  ),
  (
    'Swedish Institute Study Scholarships',
    'The Swedish Institute Study Scholarships (SISS) are awarded to highly qualified students from select countries to pursue master\'s level studies in Sweden.',
    'Swedish Universities',
    'Sweden',
    'graduate',
    ARRAY['Sustainability', 'Innovation', 'Social Sciences', 'Technology', 'Life Sciences'],
    'full_scholarship',
    38000,
    '2024-02-01 23:59:59+00',
    'https://si.se/',
    ARRAY['Developing country citizenship', 'Bachelor\'s degree', 'Leadership experience', 'English proficiency'],
    true,
    NOW(),
    NOW()
  ),
  (
    'Korea Government Scholarship Program',
    'The Korean Government Scholarship Program (KGSP) invites international students to study in Korea for both undergraduate and graduate degree programs.',
    'Korean Universities',
    'South Korea',
    'both',
    ARRAY['Korean Studies', 'Technology', 'Engineering', 'Business', 'International Relations'],
    'full_scholarship',
    45000,
    '2024-03-31 23:59:59+00',
    'https://www.studyinkorea.go.kr/',
    ARRAY['Academic excellence', 'Age requirements', 'Health requirements', 'Korean language commitment'],
    true,
    NOW(),
    NOW()
  ),
  (
    'Eiffel Excellence Scholarship Programme',
    'The Eiffel scholarship programme was designed by the French Ministry for Europe and Foreign Affairs to attract top foreign students to enroll in master\'s and PhD programs at French higher education institutions.',
    'French Universities',
    'France',
    'graduate',
    ARRAY['Engineering', 'Sciences', 'Economics', 'Law', 'Political Science'],
    'partial_scholarship',
    1400,
    '2024-01-08 23:59:59+00',
    'https://www.campusfrance.org/',
    ARRAY['Master\'s or PhD application', 'Academic excellence', 'Age limit 30 for Master\'s', 'Non-French nationality'],
    true,
    NOW(),
    NOW()
  ),
  (
    'Rotary Peace Fellowships',
    'Rotary Peace Fellowships enable leaders from around the world to study peace and conflict resolution and prevention approaches at one of the Rotary Peace Centers.',
    'Rotary Peace Centers',
    'Various Countries',
    'graduate',
    ARRAY['Peace Studies', 'Conflict Resolution', 'International Relations', 'Public Policy', 'Development'],
    'full_scholarship',
    75000,
    '2024-05-31 23:59:59+00',
    'https://www.rotary.org/',
    ARRAY['Bachelor\'s degree', 'Work experience in peace/development', 'Language requirements', 'Leadership commitment'],
    true,
    NOW(),
    NOW()
  );

-- Insert some additional scholarships with different criteria for better filtering
INSERT INTO scholarships (
  title, 
  description, 
  university, 
  country, 
  degree_level, 
  field_of_study, 
  funding_type, 
  amount, 
  deadline, 
  application_url, 
  eligibility_criteria, 
  is_active
) VALUES
  (
    'MIT Graduate Fellowships',
    'MIT offers various fellowship opportunities for graduate students pursuing advanced degrees in science, technology, engineering, and mathematics.',
    'Massachusetts Institute of Technology',
    'United States',
    'phd',
    ARRAY['Computer Science', 'Engineering', 'Physics', 'Mathematics'],
    'partial_scholarship',
    30000,
    '2024-12-15 23:59:59+00',
    'https://web.mit.edu/',
    ARRAY['PhD admission to MIT', 'Academic excellence', 'Research proposal', 'GRE scores'],
    true
  ),
  (
    'Oxford-Weidenfeld and Hoffmann Scholarships',
    'The Oxford-Weidenfeld and Hoffmann Scholarships and Leadership Programme provides graduate scholarships to students from developing and emerging economies.',
    'University of Oxford',
    'United Kingdom',
    'graduate',
    ARRAY['Public Policy', 'Development', 'Social Sciences', 'Economics'],
    'partial_scholarship',
    25000,
    '2025-01-06 23:59:59+00',
    'https://www.ox.ac.uk/',
    ARRAY['Developing country origin', 'Leadership potential', 'Academic merit', 'Return commitment'],
    true
  ),
  (
    'Technical University of Munich Scholarships',
    'TUM offers various scholarship programs for international students pursuing engineering and technical degrees.',
    'Technical University of Munich',
    'Germany',
    'undergraduate',
    ARRAY['Engineering', 'Computer Science', 'Technology', 'Applied Sciences'],
    'partial_scholarship',
    6000,
    '2024-07-15 23:59:59+00',
    'https://www.tum.de/',
    ARRAY['High school diploma', 'Academic excellence', 'German language skills helpful', 'STEM focus'],
    true
  );
