-- Insert sample scholarship data
INSERT INTO scholarships (title, description, amount, currency, deadline, eligibility_criteria, requirements, application_url, organization, country, field_of_study, level_of_study, status) VALUES
(
    'Gates Cambridge Scholarship',
    'The Gates Cambridge Scholarship is one of the most prestigious international scholarships, awarded to outstanding applicants from countries outside the UK to pursue a full-time postgraduate degree at the University of Cambridge.',
    45000.00,
    'GBP',
    '2025-12-01',
    ARRAY['International students (non-UK)', 'Outstanding academic achievement', 'Leadership potential', 'Commitment to improving lives of others'],
    ARRAY['Complete online application', 'Academic transcripts', 'Three letters of recommendation', 'Personal statement', 'Research proposal (for research degrees)'],
    'https://www.gatescambridge.org/apply',
    'Gates Cambridge Trust',
    'United Kingdom',
    ARRAY['Any field'],
    ARRAY['graduate', 'postgraduate'],
    'active'
),
(
    'Fulbright Foreign Student Program',
    'The Fulbright Foreign Student Program enables graduate students, young professionals, and artists from abroad to study and conduct research in the United States.',
    30000.00,
    'USD',
    '2025-10-15',
    ARRAY['International students', 'Bachelor''s degree or equivalent', 'English proficiency', 'Leadership qualities'],
    ARRAY['Online application', 'Academic records', 'English test scores', 'Three recommendation letters', 'Statement of purpose'],
    'https://foreign.fulbrightonline.org',
    'U.S. Department of State',
    'United States',
    ARRAY['Any field'],
    ARRAY['graduate', 'postgraduate'],
    'active'
),
(
    'DAAD Study Scholarships',
    'DAAD scholarships support international students and researchers in Germany, promoting academic exchange and international cooperation.',
    850.00,
    'EUR',
    '2025-11-30',
    ARRAY['International students', 'Completed undergraduate degree', 'German or English language skills', 'Academic excellence'],
    ARRAY['Online application', 'CV', 'Motivation letter', 'Academic transcripts', 'Language certificates', 'Two recommendation letters'],
    'https://www.daad.de/en/',
    'German Academic Exchange Service (DAAD)',
    'Germany',
    ARRAY['Engineering', 'Natural Sciences', 'Social Sciences', 'Arts'],
    ARRAY['graduate', 'postgraduate'],
    'active'
),
(
    'Chevening Scholarships',
    'Chevening Scholarships are the UK government''s global scholarship programme, funded by the Foreign and Commonwealth Office and partner organisations.',
    35000.00,
    'GBP',
    '2025-11-02',
    ARRAY['Citizens of Chevening-eligible countries', 'Undergraduate degree', 'At least two years work experience', 'Leadership potential'],
    ARRAY['Online application', 'Academic transcripts', 'Two references', 'Personal statement', 'Career plan'],
    'https://www.chevening.org/apply',
    'UK Government',
    'United Kingdom',
    ARRAY['Any field'],
    ARRAY['graduate'],
    'active'
),
(
    'Erasmus Mundus Joint Master Degrees',
    'Erasmus Mundus Joint Master Degrees are prestigious integrated study programmes jointly delivered by consortia of higher education institutions from different countries.',
    25000.00,
    'EUR',
    '2025-01-15',
    ARRAY['Bachelor''s degree', 'English proficiency', 'Academic excellence', 'International mobility'],
    ARRAY['Online application via programme website', 'Academic transcripts', 'English test scores', 'CV', 'Motivation letter', 'References'],
    'https://ec.europa.eu/programmes/erasmus-plus/',
    'European Commission',
    'European Union',
    ARRAY['Various fields depending on programme'],
    ARRAY['graduate'],
    'active'
),
(
    'Australia Awards Scholarships',
    'Australia Awards Scholarships are long-term awards administered by the Australian Government that provide opportunities for people from developing countries to undertake study at Australian universities.',
    40000.00,
    'AUD',
    '2025-04-30',
    ARRAY['Citizens of eligible developing countries', 'Undergraduate degree', 'English proficiency', 'Development impact potential'],
    ARRAY['Online application', 'Academic transcripts', 'English test scores', 'CV', 'Development impact statement', 'Two references'],
    'https://www.australiaawards.gov.au',
    'Australian Government',
    'Australia',
    ARRAY['Agriculture', 'Education', 'Health', 'Public Policy', 'Engineering'],
    ARRAY['graduate', 'postgraduate'],
    'active'
),
(
    'Joint Japan World Bank Graduate Scholarship',
    'The Joint Japan/World Bank Graduate Scholarship Program (JJ/WBGSP) provides scholarships for developing country nationals to pursue development-related studies in universities around the world.',
    50000.00,
    'USD',
    '2025-03-31',
    ARRAY['Nationals of World Bank member developing countries', 'Bachelor''s degree', 'Development work experience', 'English proficiency'],
    ARRAY['Online application', 'Academic records', 'Professional references', 'Development essay', 'English test scores'],
    'https://www.worldbank.org/en/programs/scholarships',
    'World Bank Group',
    'Various',
    ARRAY['Development Studies', 'Economics', 'Public Policy', 'Health', 'Education'],
    ARRAY['graduate'],
    'active'
),
(
    'Chinese Government Scholarship',
    'The Chinese Government Scholarship is established by the Ministry of Education (MOE) of the People''s Republic of China to support international students and scholars.',
    2500.00,
    'USD',
    '2025-03-15',
    ARRAY['International students', 'High school diploma for undergraduate', 'Bachelor''s degree for graduate', 'Good health', 'Good academic record'],
    ARRAY['Application form', 'Academic transcripts', 'Health certificate', 'Two recommendation letters', 'Study plan'],
    'https://www.studyinchina.edu.cn',
    'Ministry of Education of China',
    'China',
    ARRAY['Chinese Language', 'Medicine', 'Engineering', 'Business', 'Arts'],
    ARRAY['undergraduate', 'graduate', 'postgraduate'],
    'active'
),
(
    'Swiss Excellence Scholarships',
    'The Swiss Excellence Scholarships promote international exchange and research cooperation between Switzerland and other countries.',
    1920.00,
    'CHF',
    '2025-12-31',
    ARRAY['Foreign researchers and artists', 'Master''s or PhD degree', 'Research proposal', 'Academic excellence'],
    ARRAY['Application form', 'CV', 'Research proposal', 'Academic transcripts', 'Two recommendation letters', 'Language certificate'],
    'https://www.sbfi.admin.ch/scholarships',
    'Swiss Confederation',
    'Switzerland',
    ARRAY['Any field', 'Arts', 'Research'],
    ARRAY['postgraduate', 'research'],
    'active'
),
(
    'Rhodes Scholarship',
    'The Rhodes Scholarship is the oldest and most celebrated international fellowship award, bringing exceptional young people from around the world to study at Oxford.',
    70000.00,
    'GBP',
    '2025-10-01',
    ARRAY['Outstanding academic achievement', 'Leadership qualities', 'Commitment to service', 'Moral character', 'Physical vigor'],
    ARRAY['Online application', 'Academic transcripts', 'Personal statement', 'CV', 'Eight references', 'Interview'],
    'https://www.rhodeshouse.ox.ac.uk/scholarships/',
    'Rhodes Trust',
    'United Kingdom',
    ARRAY['Any field'],
    ARRAY['graduate', 'postgraduate'],
    'active'
);

-- Note: You can run this SQL in your Supabase SQL editor to populate the database with sample data
